"""nullable column for returnDate

Revision ID: 06e0624aced8
Revises: d08e7a95949e
Create Date: 2025-08-28 23:00:20.605082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e0624aced8'
down_revision: Union[str, Sequence[str], None] = 'd08e7a95949e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'borrowDate',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'borrowDate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
